name: VeeR-EL2 CI

on:
  push:
  pull_request:

jobs:

  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Install utils
        run: |
          sudo apt -qqy update && sudo apt -qqy install git autoconf automake \
            autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev \
            gawk build-essential bison flex texinfo gperf libtool patchutils \
            bc zlib1g zlib1g-dev libexpat-dev ninja-build cpanminus \
            ccache libfl2 libfl-dev gcc-riscv64-unknown-elf picolibc-riscv64-unknown-elf
          sudo cpanm Bit::Vector

      - name: Build Verilator
        run: |
          git clone https://github.com/verilator/verilator
          pushd verilator
            git checkout v5.002
            autoconf
            ./configure --prefix=/opt/verilator
            make -j `nproc`
            make install
          popd
 
      - name: Setup repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Run tests (Verilator)
        run: |
          export PATH=/opt/verilator/bin:$PATH
          export RV_ROOT=`pwd`
          $RV_ROOT/configs/veer.config
          make -f $RV_ROOT/tools/Makefile verilator
